#! /bin/sh

echo 'build-env: aclocal'
if `which aclocal`
then
  aclocal
else
  echo 'Environment setup failed. Install aclocal.'
  exit 1
fi

echo 'build-env: autoconf'
if `which autoconf`
then
  autoconf
else
  echo 'Environment setup failed. Install autoconf.'
  exit 1
fi

echo 'build-env: automake --add-missing'
if `which automake`
then
  automake --add-missing
else
  echo 'Environment setup failed. Install automake.'
  exit 1
fi

echo 'build-env: autoreconf'
if `which autoreconf`
then
  autoreconf
else
  echo 'Environment setup failed. Install autoreconf.'
  exit 1
fi

echo 'build-env: automake'
automake

echo 'build-env: ./configure'
./configure

echo 'Your environment setup is complete.'
exit 0
